from ..mathbase import *
from .symexpr import *
from ..mathbase import _Sin, _Cos, _Exp, _Log, _Tan, _Abs, _Real, _Imag


class _MathTyping:
    def __new__(cls, arg, simplify = True)->Expr:...

class sin(Expr, _MathTyping, _Sin):...

class cos(Expr, _MathTyping, _Cos):...

class exp(Expr, _MathTyping, _Exp):...

class log(Expr, _MathTyping, _Log):...

class tan(Expr, _MathTyping, _Tan):...

class Abs(Expr, _MathTyping, _Abs):...

class Real(Expr, _MathTyping, _Real):...

class Imag(Expr, _MathTyping, _Imag):...